config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionManager
  # protect_from_forgery with: :exception
end

app/controllers/concerns/session_manager.rb
module SessionManager
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_user! if self.respond_to?(:before_action)
  end

  def create_session
    session[:user_id] = "Current User Id"
    redirect_to root_path and return
  end

  def destroy_session
    session.delete(:user_id)
    redirect_to new_session_path and return
  end

  def user_signed?
    session[:user_id].present?
  end

  private
    def authenticate_user!
      redirect_to new_session_path and return unless session[:user_id].present?
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new

  end

  def create
    create_session
  end

  def destroy
    destroy_session
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionManager
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Session Example</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container content-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/"> Searcher </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <% if user_signed? %>
        <li class="nav-item">
          <%= link_to 'Logout', session_path, method: :delete, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      <form action="" class="form-inline my-2 my-lg-0">
        <input name="search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" value="<%= params[:search] %>">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<p> </p>